### ISSUE TITLE
Vue template issue

### ISSUE THREAD

**Issue by radeva** [amirhosseinab/stylnginfo#2]
Hi @amirhosseinab ,

I posted an [issue](https://github.com/amirhosseinab/tns-template-blank-vue/issues/1) few days ago regarding the vue template, but since I cannot see any activity there, I'm trying to reach you via this repository.

We're trying to publish a fully functional NativeScript Vue Blank template to NPM, but noticed that you have published the one having the same name almost an year ago. From the package, the repo and the downloads from NPM it is visible that the package is empty and not used.

Would you mind unpublishing the npm package so that NativeScript Vue community can get advantage of the fully functional one we're planning to publish?

Thanks in advance for your cooperation!

Veselina Radeva,
NativeScript Core Team

**Comment by amirhosseinab** [comment]
Please follow up by the original [issue](https://github.com/amirhosseinab/tns-template-blank-vue/issues/1#issuecomment-426245689)
